# ----------------------------------------------------------- #
# Note: this file is automatically managed in template-docker #
# ----------------------------------------------------------- #

on:
  - push
  - workflow_dispatch

name: push

jobs:
  metadata:
    runs-on: ubuntu-latest

    outputs:
      image-name: ${{ steps.image.outputs.name }}
      repository: ${{ steps.metadata.outputs.repository }}

    steps:
      - uses: actions/checkout@v3

      - uses: ahmadnassri/action-metadata@v1
        id: metadata

      - id: image
        run: echo "::set-output name=name::$(basename "${GITHUB_REPOSITORY/docker-//}")"

  commit-lint:
    timeout-minutes: 5

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: ahmadnassri/action-commit-lint@v1
        with:
          config: .github/linters/.commit-lint.yml

  super-linter:
    timeout-minutes: 5

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: github/super-linter/slim@v4
        env:
          LOG_LEVEL: ERROR
          IGNORE_GITIGNORED_FILES: true
          VALIDATE_ALL_CODEBASE: false
          FILTER_REGEX_EXCLUDE: '/github/workspace/README.md|test/fixtures/*'
          GITHUB_TOKEN: ${{ github.token }}

  publish-strategy:
    timeout-minutes: 5

    runs-on: ubuntu-latest

    outputs:
      matrix: ${{ steps.parse.outputs.matrix }}

    steps:
      - uses: actions/checkout@v3
      - id: parse
        run: echo "::set-output name=matrix::$(jq -c . < .github/publish-matrix.json)"

  release:
    timeout-minutes: 5

    needs:
      - commit-lint
      - super-linter

    # only runs on main branch
    if: ${{ github.ref == 'refs/heads/master' }}

    runs-on: ubuntu-latest

    outputs:
      published: ${{ steps.release.outputs.published }}
      release-version: ${{ steps.release.outputs.release-version }}
      release-version-major: ${{ steps.release.outputs.release-version-major }}
      release-version-minor: ${{ steps.release.outputs.release-version-minor }}

    steps:
      - uses: actions/checkout@v3
      - id: release
        uses: ahmadnassri/action-semantic-release@v2
        with:
          config: ${{ github.workspace }}/.semantic.json
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

  publish:
    needs:
      - release
      - metadata
      - publish-strategy

    timeout-minutes: 10

    if: ${{ needs.release.outputs.published == 'true' }}

    name: ${{ format('publish to {0}', matrix.registry) || 'publish-step' }}

    strategy:
      matrix: ${{ fromJSON(needs.publish-strategy.outputs.matrix) }}

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2

      # login to registry
      - uses: docker/login-action@v2
        with:
          registry: ${{ matrix.registry }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets[format('{0}_TOKEN', matrix.id)] }}

      # publish
      - uses: docker/build-push-action@v3
        with:
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          tags: |
            ${{ matrix.registry }}/${{ github.repository_owner }}/${{ needs.metadata.outputs.image-name }}:latest
            ${{ matrix.registry }}/${{ github.repository_owner }}/${{ needs.metadata.outputs.image-name }}:${{ needs.release.outputs.release-version-major }}
            ${{ matrix.registry }}/${{ github.repository_owner }}/${{ needs.metadata.outputs.image-name }}:${{ needs.release.outputs.release-version }}
          labels: |
            org.opencontainers.image.title=${{ needs.metadata.outputs.image-name }}
            org.opencontainers.image.url=${{ github.event.repository.html_url }}
            org.opencontainers.image.version=${{ needs.release.outputs.release-version }}
            org.opencontainers.image.source=${{ github.event.repository.html_url }}
            org.opencontainers.image.revision=${{ github.sha }}

      - name: update description
        if: ${{ matrix.registry == 'docker.io' }}
        run: |
          JWT=$(curl -s -d "username=${{ github.repository_owner }}&password=${{ secrets.DOCKER_TOKEN }}" https://hub.docker.com/v2/users/login/ | jq -r .token)
          http --quiet PATCH "https://hub.docker.com/v2/repositories/${{ github.repository_owner }}/$IMAGE" "Authorization: JWT ${JWT}" "description=${{ github.event.repository.description }}" full_description=@README.md


  template-sync:
    timeout-minutes: 20

    needs:
      - metadata
      - release
      - commit-lint
      - super-linter

    # only runs on main branch and only for the template
    if: ${{ github.ref == 'refs/heads/master' && fromJSON(needs.metadata.outputs.repository).is_template }}

    runs-on: ubuntu-latest

    steps:
      - uses: ahmadnassri/action-workflow-queue@v1.1

      - uses: actions/checkout@v3

      - uses: ahmadnassri/action-template-repository-sync@v1.6.0
        with:
          github-token: ${{ secrets.GH_TOKEN }}
