name: lint

on:
  push:
    branches-ignore:
      - master

jobs:
  super-linter:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: docker://github/super-linter:v2.0.0